kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../apps/price-optimisation/envs/prod
- ../../apps/price-planning/envs/prod

components:
- ../../variants/prod

replicas:
- name: price-optimisation
  count: 3

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: price-planning
    spec:
      template:
        spec:
          containers:
          - name: price-planning
            resources:
              requests:
                memory: 15Mi
              limits:
                memory: 15Mi
