kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../apps/price-optimisation/envs/prod
- ../../apps/price-planning/envs/prod

components:
- ../../variants/prod

replicas:
- name: price-optimisation
  count: 2

patchesStrategicMerge:
- price-planning-resources.yaml
