apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-planning
spec:
  template:
    spec:
      containers:
      - name: price-planning
        resources:
          requests:
            cpu: 0.01
            memory: 15Mi
          limits:
            cpu: 0.02
            memory: 15Mi