apiVersion: batch/v1
kind: Job
metadata:
  name: price-optimisation-db-migration
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: price-optimisation-db-migration
        image: alpine:latest
        command:
          - "/bin/sh"
          - "-ec"
          - "echo 'Starting migration' && sleep 5 && echo 'Migration finished'"
      restartPolicy: Never
  backoffLimit: 2