kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

commonLabels:
  app.kubernetes.io/name: price-planning

labels:
- pairs:
    tags.datadoghq.com/service: price-planning
  includeSelectors: false
  includeTemplates: true

resources:
- deployment.yaml
- service.yaml
