kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../apps/price-optimisation/envs/prod
- ../../apps/price-planning/envs/prod
- ../../apps/competitive-pricing/envs/prod

components:
- ../../variants/prod