apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-planning
  labels:
    tags.datadoghq.com/version: 1.3.0
spec:
  template:
    metadata:
      labels:
        tags.datadoghq.com/version: 1.3.0
    spec:
      containers:
      - name: price-planning
        image: larsaifora/echo-service:1.3.0